# Generated by Django 2.2.5 on 2020-01-13 13:43

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('presente', models.BooleanField(blank=True, default=False, null=True, verbose_name='Presente')),
                ('justificacion', models.TextField(blank=True, null=True, verbose_name='Justificacion')),
                ('fecha', models.DateField(verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id_barrio', models.AutoField(primary_key=True, serialize=False)),
                ('barrio', models.CharField(max_length=50, verbose_name='Barrio')),
                ('borrado', models.BooleanField(default=False, verbose_name='borrado')),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('telefono', models.CharField(max_length=255, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=255, verbose_name='Direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id_domicilio', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('nro', models.CharField(max_length=50, verbose_name='Numero')),
                ('mz', models.CharField(blank=True, max_length=50, null=True, verbose_name='Manzana')),
                ('departamento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Departamento')),
                ('piso', models.CharField(blank=True, max_length=50, null=True, verbose_name='Piso')),
                ('borrado', models.BooleanField(default=False, verbose_name='borrado')),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id_encuesta', models.AutoField(primary_key=True, serialize=False)),
                ('envio', models.CharField(blank=True, choices=[('Semanalmente', 'Semanalmente'), ('Mensualmente', 'Mensualmente'), ('Anualmente', 'Anualmente')], max_length=50, null=True, verbose_name='Envio')),
                ('borrado', models.BooleanField(default=False, verbose_name='borrado')),
                ('motivo', models.CharField(choices=[('Faltas', 'Faltas'), ('Estado de las Reuniones', 'Estado de las Reuniones')], max_length=50, verbose_name='Motivo')),
                ('cantidad', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de Faltas')),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Civil',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=20, verbose_name='soltero/a')),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Miembro',
            fields=[
                ('id_estado_miembro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Reunion',
            fields=[
                ('id_estado_reunion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('desde', models.IntegerField(null=True, verbose_name='edad')),
                ('hasta', models.IntegerField(null=True, verbose_name='edad')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Ambos', 'Ambos')], max_length=20, null=True, verbose_name='Sexo')),
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('borrado', models.BooleanField(default=False, verbose_name='borrado')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalMiembro',
            fields=[
                ('dni', models.BigIntegerField(db_index=True, verbose_name='Documento')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=200, verbose_name='Apellido')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('cant_hijo', models.IntegerField(null=True, verbose_name='Cantidad de Hijos')),
                ('trabaja', models.BooleanField(default=False, verbose_name='Trabaja')),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, verbose_name='e-mail')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=20, null=True, verbose_name='Sexo')),
                ('borrado', models.BooleanField(default=False, verbose_name='borrado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical miembro',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Horario_Disponible',
            fields=[
                ('id_horario_disponible', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(blank=True, choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], max_length=50, null=True, verbose_name='dia')),
                ('desde', models.TimeField(blank=True, null=True, verbose_name='Desde')),
                ('hasta', models.TimeField(blank=True, null=True, verbose_name='Hasta')),
                ('borrado', models.BooleanField(default=False, verbose_name='borrado')),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('dni', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Documento')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=200, verbose_name='Apellido')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('cant_hijo', models.IntegerField(null=True, verbose_name='Cantidad de Hijos')),
                ('trabaja', models.BooleanField(default=False, verbose_name='Trabaja')),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, verbose_name='e-mail')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=20, null=True, verbose_name='Sexo')),
                ('borrado', models.BooleanField(default=False, verbose_name='borrado')),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema.Domicilio')),
                ('estado_civil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema.Estado_Civil')),
                ('horario_disponible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema.Horario_Disponible')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, verbose_name='Pregunta')),
                ('borrado', models.BooleanField(default=False, verbose_name='borrado')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('provincia', models.CharField(max_length=50, verbose_name='Provincia')),
                ('borrado', models.BooleanField(default=False, verbose_name='borrado')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Reunion',
            fields=[
                ('id_tipo_reunion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=200, null=True, verbose_name='Descripcion')),
                ('borrado', models.BooleanField(default=False, verbose_name='borrado')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Telefono',
            fields=[
                ('id_tipo_telefono', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, choices=[('Fijo', 'Fijo'), ('Movil', 'Movil')], max_length=50, null=True, verbose_name='Tipo')),
                ('empresa', models.CharField(blank=True, choices=[('Movistar', 'Movistar'), ('Otro', 'Otro'), ('Tuenti', 'Tuenti'), ('Claro', 'Claro'), ('Personal', 'Personal')], max_length=50, null=True, verbose_name='Empresa')),
                ('borrado', models.BooleanField(default=False, verbose_name='borrado')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPregunta',
            fields=[
                ('id_tipo_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Abierta', 'Abierta'), ('Unica Opcion Positiva', 'Unica Opcion Positiva'), ('Unica Opcion Negativa', 'Unica Opcion Negativa'), ('Opcion multiple', 'Opcion multiple')], max_length=50, verbose_name='Tipo')),
                ('borrado', models.BooleanField(default=False, verbose_name='borrado')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono_Contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema.Miembro')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id_telefono', models.AutoField(primary_key=True, serialize=False)),
                ('prefijo', models.IntegerField(blank=True, null=True, verbose_name='Prefijo')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='Numero')),
                ('whatsapp', models.BooleanField(default=True, verbose_name='Whatsapp')),
                ('borrado', models.BooleanField(default=False, verbose_name='borrado')),
                ('tipo_telefono', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sistema.Tipo_Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id_reunion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('borrado', models.BooleanField(default=False, verbose_name='borrado')),
                ('domicilio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sistema.Domicilio')),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sistema.Grupo')),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Horario_Disponible')),
                ('tipo_reunion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema.Tipo_Reunion')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, verbose_name='Respuesta')),
                ('puntaje', models.IntegerField(verbose_name='Puntaje')),
                ('borrado', models.BooleanField(default=False, verbose_name='borrado')),
                ('pregunta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sistema.Pregunta')),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema.TipoPregunta'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='telefono',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sistema.Telefono'),
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_localidad', models.AutoField(primary_key=True, serialize=False)),
                ('localidad', models.CharField(max_length=50, verbose_name='Localidad')),
                ('borrado', models.BooleanField(default=False, verbose_name='borrado')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema.Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalReunion',
            fields=[
                ('id_reunion', models.IntegerField(blank=True, db_index=True)),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('borrado', models.BooleanField(default=False, verbose_name='borrado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('domicilio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sistema.Domicilio')),
                ('grupo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sistema.Grupo')),
            ],
            options={
                'verbose_name': 'historical reunion',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
