# Generated by Django 2.2.5 on 2019-09-25 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id_domicilio', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('nro', models.CharField(max_length=50, verbose_name='Numero')),
                ('mz', models.CharField(max_length=50, null=True, verbose_name='Manzana')),
                ('barrio', models.CharField(max_length=100, verbose_name='Barrio')),
                ('localidad', models.CharField(max_length=50, verbose_name='Localidad')),
                ('provincia', models.CharField(max_length=50, verbose_name='Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id_fecha_envio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_envio', models.DateField(verbose_name='Fecha Envio')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, verbose_name='Pregunta')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Reunion',
            fields=[
                ('id_tipo_reunion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=200, null=True, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Telefono',
            fields=[
                ('id_tipo_telefono', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('empresa', models.CharField(max_length=50, verbose_name='Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id_telefono', models.AutoField(primary_key=True, serialize=False)),
                ('prefijo', models.IntegerField(verbose_name='Prefijo')),
                ('numero', models.IntegerField(verbose_name='Numero')),
                ('whatsapp', models.BooleanField(verbose_name='Whatsapp')),
                ('tipo_telefono', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Tipo_Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id_reunion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Horario')),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('domicilio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Domicilio')),
                ('tipo_reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Tipo_Reunion')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, verbose_name='Respuesta')),
                ('puntaje', models.IntegerField(verbose_name='Puntaje')),
                ('pregunta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sistema.Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('tipo_dni', models.CharField(choices=[('DNI', 'DNI'), ('CUIL', 'CUIL'), ('CUIT', 'CUIT'), ('PASAPORTE', 'PASAPORTE')], max_length=20, verbose_name='Tipo de DNI')),
                ('dni', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Documento')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=200, verbose_name='Apellido')),
                ('nacionalidad', models.CharField(max_length=100, verbose_name='Nacionalidad')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('estado_civil', models.CharField(choices=[('Soltero/a', 'Soltero/a'), ('Casado/a', 'Casado/a'), ('Divorciado/a', 'Divorciado/a'), ('Viudo/a', 'Viudo/a')], max_length=20, verbose_name='Estado Civil')),
                ('cant_hijo', models.IntegerField(null=True, verbose_name='Cantidad de Hijos')),
                ('trabaja', models.BooleanField(default=False, verbose_name='Trabaja')),
                ('correo', models.EmailField(max_length=100, null=True, verbose_name='e-mail')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=20, null=True, verbose_name='Sexo')),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Domicilio')),
                ('telefono', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='Horario_Disponible',
            fields=[
                ('id_horario_disponible', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=50, verbose_name='Tipo')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Miembro')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('miembro', models.ManyToManyField(to='sistema.Miembro')),
            ],
        ),
        migrations.AddField(
            model_name='encuesta',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Miembro'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('presente', models.BooleanField(verbose_name='Presente')),
                ('justificacion', models.TextField(null=True, verbose_name='Justificacion')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Miembro')),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Reunion')),
            ],
        ),
    ]
