# Generated by Django 2.2.5 on 2019-09-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_reunion',
            name='Descripcion',
        ),
        migrations.AddField(
            model_name='tipo_reunion',
            name='descripcion',
            field=models.CharField(max_length=200, null=True, verbose_name='Descripcion'),
        ),
    ]
