# Generated by Django 2.2.5 on 2019-09-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilio',
            name='departamento',
            field=models.CharField(max_length=50, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='piso',
            field=models.CharField(max_length=50, null=True, verbose_name='Piso'),
        ),
    ]
