# Generated by Django 2.2.5 on 2019-09-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefono',
            name='prefijo',
            field=models.IntegerField(default=3764, verbose_name='Prefijo'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(choices=[('Movistar', 'Movistar'), ('Claro', 'Claro'), ('Otro', 'Otro'), ('Tuenti', 'Tuenti'), ('Personal', 'Personal')], max_length=50, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='tipo',
            field=models.CharField(choices=[('Fijo', 'Fijo'), ('Movil', 'Movil')], max_length=50, verbose_name='Tipo'),
        ),
    ]
