# Generated by Django 2.2.5 on 2019-10-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembro',
            name='nacionalidad',
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(choices=[('Claro', 'Claro'), ('Movistar', 'Movistar'), ('Tuenti', 'Tuenti'), ('Personal', 'Personal'), ('Otro', 'Otro')], max_length=50, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='tipo',
            field=models.CharField(choices=[('Fijo', 'Fijo'), ('Movil', 'Movil')], max_length=50, verbose_name='Tipo'),
        ),
    ]
