# Generated by Django 2.2 on 2020-03-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20200303_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreunion',
            name='nombre',
            field=models.CharField(max_length=100, null=True, verbose_name=' Nombre (*)'),
        ),
        migrations.AlterField(
            model_name='historicaltipo_reunion',
            name='descripcion',
            field=models.CharField(max_length=200, null=True, verbose_name='Descripcion (*)'),
        ),
        migrations.AlterField(
            model_name='historicaltipo_reunion',
            name='frecuencia',
            field=models.IntegerField(verbose_name='Frecuencia (*)'),
        ),
        migrations.AlterField(
            model_name='historicaltipo_reunion',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre (*)'),
        ),
        migrations.AlterField(
            model_name='reunion',
            name='nombre',
            field=models.CharField(max_length=100, null=True, verbose_name=' Nombre (*)'),
        ),
        migrations.AlterField(
            model_name='tipo_reunion',
            name='descripcion',
            field=models.CharField(max_length=200, null=True, verbose_name='Descripcion (*)'),
        ),
        migrations.AlterField(
            model_name='tipo_reunion',
            name='frecuencia',
            field=models.IntegerField(verbose_name='Frecuencia (*)'),
        ),
        migrations.AlterField(
            model_name='tipo_reunion',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre (*)'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Movistar', 'Movistar'), ('Personal', 'Personal'), ('Tuenti', 'Tuenti'), ('Claro', 'Claro'), ('Otro', 'Otro')], max_length=50, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Movil', 'Movil'), ('Fijo', 'Fijo')], max_length=50, null=True, verbose_name='Tipo'),
        ),
    ]
