# Generated by Django 2.2.5 on 2019-09-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20190925_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='presente',
            field=models.BooleanField(default=False, verbose_name='Presente'),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='whatsapp',
            field=models.BooleanField(default=True, verbose_name='Whatsapp'),
        ),
    ]
