# Generated by Django 2.2.5 on 2019-11-10 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20191109_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefono_contacto',
            name='miembro',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.PROTECT, to='sistema.Miembro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Movistar', 'Movistar'), ('Otro', 'Otro'), ('Personal', 'Personal'), ('Tuenti', 'Tuenti'), ('Claro', 'Claro')], max_length=50, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Fijo', 'Fijo'), ('Movil', 'Movil')], max_length=50, null=True, verbose_name='Tipo'),
        ),
    ]
