# Generated by Django 2.2.5 on 2019-09-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20190927_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='mz',
            field=models.CharField(max_length=50, null=True, verbose_name='Manzana'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(choices=[('Otro', 'Otro'), ('Personal', 'Personal'), ('Claro', 'Claro'), ('Movistar', 'Movistar'), ('Tuenti', 'Tuenti')], max_length=50, verbose_name='Empresa'),
        ),
    ]
