# Generated by Django 2.2.5 on 2019-10-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20191002_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(choices=[('Movistar', 'Movistar'), ('Personal', 'Personal'), ('Claro', 'Claro'), ('Otro', 'Otro'), ('Tuenti', 'Tuenti')], max_length=50, verbose_name='Empresa'),
        ),
    ]
