# Generated by Django 2.2.5 on 2019-09-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20190915_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='nombre',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
    ]
