# Generated by Django 2.2.5 on 2019-10-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_auto_20191002_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefono',
            name='prefijo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Prefijo'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(choices=[('Tuenti', 'Tuenti'), ('Otro', 'Otro'), ('Claro', 'Claro'), ('Personal', 'Personal'), ('Movistar', 'Movistar')], max_length=50, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='tipo',
            field=models.CharField(choices=[('Movil', 'Movil'), ('Fijo', 'Fijo')], max_length=50, verbose_name='Tipo'),
        ),
    ]
