# Generated by Django 2.2.5 on 2019-10-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_auto_20190927_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='borrado',
            field=models.BooleanField(default=False, verbose_name='borrado'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Movistar', 'Movistar'), ('Claro', 'Claro'), ('Tuenti', 'Tuenti'), ('Otro', 'Otro')], max_length=50, verbose_name='Empresa'),
        ),
    ]
