# Generated by Django 2.2.5 on 2019-09-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_reunion_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilio',
            name='mz',
            field=models.CharField(max_length=50, null=True, verbose_name='Manzana'),
        ),
    ]
