# Generated by Django 2.2.5 on 2019-09-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_auto_20190925_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='mz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Manzana'),
        ),
    ]
