# Generated by Django 2.2.5 on 2019-12-02 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_auto_20191201_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reunion',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='reunion',
            name='hora',
        ),
        migrations.AddField(
            model_name='reunion',
            name='edad',
            field=models.IntegerField(null=True, verbose_name='edad'),
        ),
        migrations.AddField(
            model_name='reunion',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Horario_Disponible'),
        ),
        migrations.AddField(
            model_name='reunion',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=20, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Otro', 'Otro'), ('Claro', 'Claro'), ('Personal', 'Personal'), ('Movistar', 'Movistar'), ('Tuenti', 'Tuenti')], max_length=50, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Fijo', 'Fijo'), ('Movil', 'Movil')], max_length=50, null=True, verbose_name='Tipo'),
        ),
    ]
