# Generated by Django 2.2 on 2020-03-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_auto_20200305_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_encuesta',
            name='aviso',
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Claro', 'Claro'), ('Personal', 'Personal'), ('Tuenti', 'Tuenti'), ('Otro', 'Otro'), ('Movistar', 'Movistar')], max_length=50, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Fijo', 'Fijo'), ('Movil', 'Movil')], max_length=50, null=True, verbose_name='Tipo'),
        ),
    ]
