# Generated by Django 2.2.5 on 2019-10-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_auto_20191002_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilio',
            name='borrado',
            field=models.BooleanField(default=False, verbose_name='borrado'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='borrado',
            field=models.BooleanField(default=False, verbose_name='borrado'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='borrado',
            field=models.BooleanField(default=False, verbose_name='borrado'),
        ),
        migrations.AddField(
            model_name='horario_disponible',
            name='borrado',
            field=models.BooleanField(default=False, verbose_name='borrado'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='borrado',
            field=models.BooleanField(default=False, verbose_name='borrado'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='borrado',
            field=models.BooleanField(default=False, verbose_name='borrado'),
        ),
        migrations.AddField(
            model_name='reunion',
            name='borrado',
            field=models.BooleanField(default=False, verbose_name='borrado'),
        ),
        migrations.AddField(
            model_name='telefono',
            name='borrado',
            field=models.BooleanField(default=False, verbose_name='borrado'),
        ),
        migrations.AddField(
            model_name='tipo_reunion',
            name='borrado',
            field=models.BooleanField(default=False, verbose_name='borrado'),
        ),
        migrations.AddField(
            model_name='tipo_telefono',
            name='borrado',
            field=models.BooleanField(default=False, verbose_name='borrado'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Otro', 'Otro'), ('Claro', 'Claro'), ('Movistar', 'Movistar'), ('Tuenti', 'Tuenti')], max_length=50, verbose_name='Empresa'),
        ),
    ]
