# Generated by Django 2.2 on 2020-03-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_auto_20200308_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmiembro',
            name='cant_hijo',
        ),
        migrations.RemoveField(
            model_name='miembro',
            name='cant_hijo',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='logo',
            field=models.BinaryField(blank=True, null=True, verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='historicalconfiguracion',
            name='logo',
            field=models.BinaryField(blank=True, null=True, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Movistar', 'Movistar'), ('Otro', 'Otro'), ('Claro', 'Claro'), ('Personal', 'Personal'), ('Tuenti', 'Tuenti')], max_length=50, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Movil', 'Movil'), ('Fijo', 'Fijo')], max_length=50, null=True, verbose_name='Tipo'),
        ),
    ]
