# Generated by Django 2.2.5 on 2019-09-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_domicilio_mz'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='tipo_dni',
            field=models.CharField(choices=[('D.N.I', 'D.N.I.'), ('CUIL', 'CUIL'), ('CUIT', 'CUIT'), ('PASAPORTE', 'PASAPORTE')], default='DNI', max_length=20, verbose_name='Tipo de DNI'),
            preserve_default=False,
        ),
    ]
