# Generated by Django 2.2.5 on 2019-12-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_auto_20191201_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reunion',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='reunion',
            name='sexo',
        ),
        migrations.AddField(
            model_name='grupo',
            name='edad',
            field=models.IntegerField(null=True, verbose_name='edad'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Ambos', 'Ambos')], max_length=20, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Otro', 'Otro'), ('Tuenti', 'Tuenti'), ('Movistar', 'Movistar'), ('Claro', 'Claro'), ('Personal', 'Personal')], max_length=50, null=True, verbose_name='Empresa'),
        ),
    ]
