# Generated by Django 2.2.5 on 2020-01-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_auto_20200125_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='justificado',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='historicalasistencia',
            name='justificado',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Claro', 'Claro'), ('Otro', 'Otro'), ('Movistar', 'Movistar'), ('Personal', 'Personal'), ('Tuenti', 'Tuenti')], max_length=50, null=True, verbose_name='Empresa'),
        ),
    ]
