# Generated by Django 2.2.5 on 2019-10-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_auto_20191002_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Movistar', 'Movistar'), ('Tuenti', 'Tuenti'), ('Claro', 'Claro'), ('Otro', 'Otro')], max_length=50, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='tipo',
            field=models.CharField(choices=[('Fijo', 'Fijo'), ('Movil', 'Movil')], max_length=50, verbose_name='Tipo'),
        ),
    ]
