# Generated by Django 2.2.5 on 2020-01-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_auto_20200125_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='fecha_respuesta',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='puntaje',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='respondio',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalencuesta',
            name='fecha_respuesta',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalencuesta',
            name='puntaje',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalencuesta',
            name='respondio',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Claro', 'Claro'), ('Otro', 'Otro'), ('Movistar', 'Movistar'), ('Tuenti', 'Tuenti'), ('Personal', 'Personal')], max_length=50, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Fijo', 'Fijo'), ('Movil', 'Movil')], max_length=50, null=True, verbose_name='Tipo'),
        ),
    ]
