# Generated by Django 2.2.5 on 2019-10-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_auto_20191002_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(choices=[('Otro', 'Otro'), ('Personal', 'Personal'), ('Movistar', 'Movistar'), ('Tuenti', 'Tuenti'), ('Claro', 'Claro')], max_length=50, verbose_name='Empresa'),
        ),
    ]
