# Generated by Django 2.2.5 on 2019-12-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_auto_20191202_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='edad',
        ),
        migrations.AddField(
            model_name='grupo',
            name='desde',
            field=models.IntegerField(null=True, verbose_name='edad'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='hasta',
            field=models.IntegerField(null=True, verbose_name='edad'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Otro', 'Otro'), ('Claro', 'Claro'), ('Tuenti', 'Tuenti'), ('Personal', 'Personal'), ('Movistar', 'Movistar')], max_length=50, null=True, verbose_name='Empresa'),
        ),
    ]
