# Generated by Django 2.2.5 on 2019-10-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_auto_20191004_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefono',
            name='numero',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Claro', 'Claro'), ('Movistar', 'Movistar'), ('Personal', 'Personal'), ('Otro', 'Otro'), ('Tuenti', 'Tuenti')], max_length=50, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Fijo', 'Fijo'), ('Movil', 'Movil')], max_length=50, null=True, verbose_name='Tipo'),
        ),
    ]
