# Generated by Django 2.2.5 on 2019-12-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_auto_20191202_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('telefono', models.CharField(max_length=255, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=255, verbose_name='Direccion')),
                ('logo', models.BinaryField(verbose_name='Logo')),
            ],
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Personal', 'Personal'), ('Claro', 'Claro'), ('Otro', 'Otro'), ('Tuenti', 'Tuenti'), ('Movistar', 'Movistar')], max_length=50, null=True, verbose_name='Empresa'),
        ),
    ]
