# Generated by Django 2.2.5 on 2020-01-25 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_auto_20200125_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='puntaje',
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Claro', 'Claro'), ('Tuenti', 'Tuenti'), ('Personal', 'Personal'), ('Otro', 'Otro'), ('Movistar', 'Movistar')], max_length=50, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Movil', 'Movil'), ('Fijo', 'Fijo')], max_length=50, null=True, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='Opciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('opcion', models.CharField(max_length=150)),
                ('puntaje', models.IntegerField()),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema.Pregunta')),
            ],
        ),
        migrations.AddField(
            model_name='respuesta',
            name='opcion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sistema.Opciones'),
            preserve_default=False,
        ),
    ]
