# Generated by Django 2.2.5 on 2020-01-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_auto_20200125_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='opciones',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Claro', 'Claro'), ('Personal', 'Personal'), ('Tuenti', 'Tuenti'), ('Otro', 'Otro'), ('Movistar', 'Movistar')], max_length=50, null=True, verbose_name='Empresa'),
        ),
    ]
