# Generated by Django 2.2.5 on 2019-12-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_auto_20191204_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='logo',
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Personal', 'Personal'), ('Movistar', 'Movistar'), ('Otro', 'Otro'), ('Tuenti', 'Tuenti'), ('Claro', 'Claro')], max_length=50, null=True, verbose_name='Empresa'),
        ),
    ]
