# Generated by Django 2.2.5 on 2019-10-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_auto_20191004_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Personal', 'Personal'), ('Otro', 'Otro'), ('Tuenti', 'Tuenti'), ('Claro', 'Claro'), ('Movistar', 'Movistar')], max_length=50, null=True, verbose_name='Empresa'),
        ),
    ]
