# Generated by Django 2.2.5 on 2019-10-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_auto_20191006_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='tipo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Mixto', 'Mixto')], default='Mixto', max_length=50, verbose_name='tipo de grupo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Otro', 'Otro'), ('Personal', 'Personal'), ('Movistar', 'Movistar'), ('Tuenti', 'Tuenti'), ('Claro', 'Claro')], max_length=50, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Movil', 'Movil'), ('Fijo', 'Fijo')], max_length=50, null=True, verbose_name='Tipo'),
        ),
    ]
