# Generated by Django 2.2.5 on 2020-01-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_auto_20200128_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario_disponible',
            name='desde',
            field=models.TimeField(blank=True, null=True, verbose_name='Desd e'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Tuenti', 'Tuenti'), ('Claro', 'Claro'), ('Movistar', 'Movistar'), ('Otro', 'Otro'), ('Personal', 'Personal')], max_length=50, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Fijo', 'Fijo'), ('Movil', 'Movil')], max_length=50, null=True, verbose_name='Tipo'),
        ),
    ]
