# Generated by Django 2.2.5 on 2019-10-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_auto_20191006_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Otro', 'Otro'), ('Movistar', 'Movistar'), ('Personal', 'Personal'), ('Claro', 'Claro'), ('Tuenti', 'Tuenti')], max_length=50, null=True, verbose_name='Empresa'),
        ),
    ]
