# Generated by Django 2.2.5 on 2020-01-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0011_auto_20200130_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpregunta',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Pregunta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Pregunta'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Claro', 'Claro'), ('Personal', 'Personal'), ('Tuenti', 'Tuenti'), ('Otro', 'Otro'), ('Movistar', 'Movistar')], max_length=50, null=True, verbose_name='Empresa'),
        ),
    ]
