# Generated by Django 2.2.5 on 2020-02-07 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0015_auto_20200201_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado_reunion',
            name='encuesta',
            field=models.ForeignKey(default=151, on_delete=django.db.models.deletion.PROTECT, to='sistema.Encuesta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Claro', 'Claro'), ('Tuenti', 'Tuenti'), ('Otro', 'Otro'), ('Movistar', 'Movistar'), ('Personal', 'Personal')], max_length=50, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Fijo', 'Fijo'), ('Movil', 'Movil')], max_length=50, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterUniqueTogether(
            name='miembro',
            unique_together={('dni', 'sexo')},
        ),
    ]
