# Generated by Django 2.2.5 on 2020-02-07 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0016_auto_20200207_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado_reunion',
            name='encuesta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sistema.Encuesta'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Personal', 'Personal'), ('Otro', 'Otro'), ('Tuenti', 'Tuenti'), ('Movistar', 'Movistar'), ('Claro', 'Claro')], max_length=50, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Movil', 'Movil'), ('Fijo', 'Fijo')], max_length=50, null=True, verbose_name='Tipo'),
        ),
    ]
