# Generated by Django 2.2.5 on 2020-02-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0017_auto_20200207_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='capacidad',
            field=models.IntegerField(default=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalgrupo',
            name='capacidad',
            field=models.IntegerField(default=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaltipo_reunion',
            name='frecuencia',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipo_encuesta',
            name='aviso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipo_reunion',
            name='frecuencia',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Tuenti', 'Tuenti'), ('Otro', 'Otro'), ('Movistar', 'Movistar'), ('Personal', 'Personal'), ('Claro', 'Claro')], max_length=50, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Fijo', 'Fijo'), ('Movil', 'Movil')], max_length=50, null=True, verbose_name='Tipo'),
        ),
    ]
