# Generated by Django 2.2.5 on 2020-03-01 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0018_auto_20200215_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='estado_reunion',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema.Estado'),
        ),
        migrations.AlterField(
            model_name='estado_reunion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tipo_telefono',
            name='empresa',
            field=models.CharField(blank=True, choices=[('Movistar', 'Movistar'), ('Personal', 'Personal'), ('Tuenti', 'Tuenti'), ('Otro', 'Otro'), ('Claro', 'Claro')], max_length=50, null=True, verbose_name='Empresa'),
        ),
    ]
