# Generated by Django 2.2.5 on 2020-01-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='faltas',
            field=models.IntegerField(null=True, verbose_name='Faltas'),
        ),
    ]
