# Generated by Django 2.2.5 on 2020-01-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_customuser_faltas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='faltas',
            field=models.IntegerField(default='0', null=True, verbose_name='Faltas'),
        ),
    ]
