# Generated by Django 2.2.5 on 2020-03-01 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0019_auto_20200301_1512'),
        ('usuario', '0004_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('confirmado', models.BooleanField(null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema.Estado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
